# AI Backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-backend
  template:
    metadata:
      labels:
        app: ai-backend
    spec:
      containers:
      - name: ai-backend
        image: localhost:32000/ai-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: AZURE_STORAGE_CONNECTION_STRING
          value: "DefaultEndpointsProtocol=https;AccountName=YOUR_STORAGE_ACCOUNT;AccountKey=YOUR_KEY;EndpointSuffix=core.windows.net"
        - name: TEXT_ANALYTICS_ENDPOINT
          value: "https://YOUR_REGION.api.cognitive.microsoft.com/"
        - name: TEXT_ANALYTICS_KEY
          value: "YOUR_TEXT_ANALYTICS_KEY"
        - name: SQL_USER
          value: "dbadmin"
        - name: SQL_PASSWORD
          value: "YOUR_SQL_PASSWORD"
        - name: SQL_DATABASE
          value: "aiapp"
        - name: SQL_SERVER
          value: "YOUR_SQL_SERVER.database.windows.net"
        - name: PORT
          value: "3001"

---
# AI Backend Service
apiVersion: v1
kind: Service
metadata:
  name: ai-backend-service
spec:
  type: NodePort
  selector:
    app: ai-backend
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30091

---
# AI Frontend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-frontend
  template:
    metadata:
      labels:
        app: ai-frontend
    spec:
      containers:
      - name: ai-frontend
        image: localhost:32000/ai-frontend:latest
        ports:
        - containerPort: 80

---
# AI Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: ai-frontend-service
spec:
  type: NodePort
  selector:
    app: ai-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30092