apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: kube-system
data:
  registries.yaml: |
    mirrors:
      "localhost:5000":
        endpoint:
          - "http://localhost:5000"